# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a build to TestFlight"
  lane :publish do
    upload_to_testflight(
      ipa: ENV['BITRISE_IPA_PATH'],
      skip_waiting_for_build_processing: true,
      changelog: ENV['BITRISE_GIT_MESSAGE'],
    )
  end
end
