export const mapLayers: { [key: string]: unknown }[] = [
  {
    id: 'background',
    type: 'background',
    paint: {
      'background-color': '#2A2A2A',
    },
  },
  {
    id: 'earth',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'earth',
    paint: {
      'fill-color': '#2A2A2A',
    },
  },
  {
    id: 'landuse_park',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'landuse',
    filter: ['any', ['==', 'pmap:kind', 'park'], ['==', 'landuse', 'cemetery']],
    paint: {
      'fill-color': '#2A2A2A',
    },
  },
  {
    id: 'landuse_hospital',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'landuse',
    filter: ['any', ['==', 'pmap:kind', 'hospital']],
    paint: {
      'fill-color': '#2A2A2A',
    },
  },
  {
    id: 'landuse_industrial',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'landuse',
    filter: ['any', ['==', 'pmap:kind', 'industrial']],
    paint: {
      'fill-color': '#2A2A2A',
    },
  },
  {
    id: 'landuse_school',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'landuse',
    filter: ['any', ['==', 'pmap:kind', 'school']],
    paint: {
      'fill-color': '#2A2A2A',
    },
  },
  {
    id: 'natural_wood',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'natural',
    filter: [
      'any',
      ['==', 'natural', 'wood'],
      ['==', 'leisure', 'nature_reserve'],
      ['==', 'landuse', 'forest'],
    ],
    paint: {
      'fill-color': '#2A2A2A',
    },
  },
  {
    id: 'landuse_pedestrian',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'landuse',
    filter: ['any', ['==', 'highway', 'footway']],
    paint: {
      'fill-color': '#2A2A2A',
    },
  },
  {
    id: 'natural_glacier',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'natural',
    filter: ['==', 'natural', 'glacier'],
    paint: {
      'fill-color': '#2A2A2A',
    },
  },
  {
    id: 'natural_sand',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'natural',
    filter: ['==', 'natural', 'sand'],
    paint: {
      'fill-color': '#2A2A2A',
    },
  },
  {
    id: 'landuse_aerodrome',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'landuse',
    filter: ['==', 'aeroway', 'aerodrome'],
    paint: {
      'fill-color': '#2A2A2A',
    },
  },
  {
    id: 'transit_runway',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'transit',
    filter: ['has', 'aeroway'],
    paint: {
      'line-color': '#2A2A2A',
      'line-width': 6,
    },
  },
  {
    id: 'landuse_runway',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'landuse',
    filter: [
      'any',
      ['==', 'aeroway', 'runway'],
      ['==', 'area:aeroway', 'runway'],
      ['==', 'area:aeroway', 'taxiway'],
    ],
    paint: {
      'fill-color': '#2A2A2A',
    },
  },
  {
    id: 'water',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'water',
    paint: {
      'fill-color': '#202020',
    },
  },
  {
    id: 'roads_tunnels_other',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['<', 'pmap:level', 0], ['==', 'pmap:kind', 'other']],
    paint: {
      'line-color': '#3D3D3D',
      'line-dasharray': [1, 1],
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        14,
        0,
        14.5,
        0.5,
        20,
        12,
      ],
    },
  },
  {
    id: 'roads_tunnels_minor',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['<', 'pmap:level', 0], ['==', 'pmap:kind', 'minor_road']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        12,
        0,
        12.5,
        0.5,
        20,
        32,
      ],
    },
  },
  {
    id: 'roads_tunnels_medium',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['<', 'pmap:level', 0], ['==', 'pmap:kind', 'medium_road']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        7,
        0,
        7.5,
        0.5,
        20,
        32,
      ],
    },
  },
  {
    id: 'roads_tunnels_major',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['<', 'pmap:level', 0], ['==', 'pmap:kind', 'major_road']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        7,
        0,
        7.5,
        0.5,
        19,
        32,
      ],
    },
  },
  {
    id: 'roads_tunnels_highway',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['<', 'pmap:level', 0], ['==', 'pmap:kind', 'highway']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        3,
        0,
        3.5,
        0.5,
        18,
        32,
      ],
    },
  },
  {
    id: 'roads_other',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['==', 'pmap:level', 0], ['==', 'pmap:kind', 'other']],
    paint: {
      'line-color': '#3D3D3D',
      'line-dasharray': [2, 1],
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        14,
        0,
        14.5,
        0.5,
        20,
        12,
      ],
    },
  },
  {
    id: 'roads_minor',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['==', 'pmap:level', 0], ['==', 'pmap:kind', 'minor_road']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        12,
        0,
        12.5,
        0.5,
        20,
        32,
      ],
    },
  },
  {
    id: 'roads_medium',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: [
      'all',
      ['==', 'pmap:level', 0],
      ['==', 'pmap:kind', 'medium_road'],
    ],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        7,
        0,
        7.5,
        0.5,
        20,
        32,
      ],
    },
  },
  {
    id: 'roads_major',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['==', 'pmap:level', 0], ['==', 'pmap:kind', 'major_road']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        7,
        0,
        7.5,
        0.5,
        19,
        32,
      ],
    },
  },
  {
    id: 'roads_highway',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['==', 'pmap:level', 0], ['==', 'pmap:kind', 'highway']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        3,
        0,
        3.5,
        0.5,
        18,
        32,
      ],
    },
  },
  {
    id: 'transit_railway',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'transit',
    filter: ['all', ['==', 'pmap:kind', 'railway']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': 2,
    },
  },
  {
    id: 'transit_railway_tracks',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'transit',
    filter: ['all', ['==', 'pmap:kind', 'railway']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': 0.8,
      'line-dasharray': [6, 10],
    },
  },
  {
    id: 'boundaries_country',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'boundaries',
    filter: ['<=', 'pmap:min_admin_level', 2],
    paint: {
      'line-color': '#696969',
      'line-width': 1.5,
    },
  },
  {
    id: 'boundaries',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'boundaries',
    filter: ['>', 'pmap:min_admin_level', 2],
    paint: {
      'line-color': '#696969',
      'line-width': 1,
      'line-dasharray': [1, 2],
    },
  },
  {
    id: 'roads_bridges_other',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['>', 'pmap:level', 0], ['==', 'pmap:kind', 'other']],
    paint: {
      'line-color': '#3D3D3D',
      'line-dasharray': [2, 1],
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        14,
        0,
        14.5,
        0.5,
        20,
        12,
      ],
    },
  },
  {
    id: 'roads_bridges_minor',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['>', 'pmap:level', 0], ['==', 'pmap:kind', 'minor_road']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        12,
        0,
        12.5,
        0.5,
        20,
        32,
      ],
    },
  },
  {
    id: 'roads_bridges_medium',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['>', 'pmap:level', 0], ['==', 'pmap:kind', 'medium_road']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        7,
        0,
        7.5,
        0.5,
        20,
        32,
      ],
    },
  },
  {
    id: 'roads_bridges_major',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['>', 'pmap:level', 0], ['==', 'pmap:kind', 'major_road']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        7,
        0,
        7.5,
        0.5,
        19,
        32,
      ],
    },
  },
  {
    id: 'roads_bridges_highway',
    type: 'line',
    source: 'protomaps',
    'source-layer': 'roads',
    filter: ['all', ['>', 'pmap:level', 0], ['==', 'pmap:kind', 'highway']],
    paint: {
      'line-color': '#3D3D3D',
      'line-width': [
        'interpolate',
        ['exponential', 1.6],
        ['zoom'],
        3,
        0,
        3.5,
        0.5,
        18,
        32,
      ],
    },
  },
  {
    id: 'physical_line_waterway_label',
    type: 'symbol',
    source: 'protomaps',
    'source-layer': 'physical_line',
    minzoom: 14,
    layout: {
      'symbol-placement': 'line',
      'text-font': ['NotoSans-Regular'],
      'text-field': ['get', 'name'],
      'text-size': 10,
      'text-letter-spacing': 0.3,
    },
    paint: {
      'text-color': '#6D6D6D',
      'text-halo-color': '#151515',
      'text-halo-width': 1,
    },
  },
  {
    id: 'roads_labels',
    type: 'symbol',
    source: 'protomaps',
    'source-layer': 'roads',
    layout: {
      'symbol-placement': 'line',
      'text-font': ['NotoSans-Regular'],
      'text-field': ['get', 'name'],
      'text-size': 12,
    },
    paint: {
      'text-color': '#6D6D6D',
      'text-halo-color': '#151515',
      'text-halo-width': 2,
    },
  },
  {
    id: 'mask',
    type: 'fill',
    source: 'protomaps',
    'source-layer': 'mask',
    paint: {
      'fill-color': '#F3F3F1',
    },
  },
  {
    id: 'physical_point_ocean',
    type: 'symbol',
    source: 'protomaps',
    'source-layer': 'physical_point',
    filter: ['any', ['==', 'place', 'sea'], ['==', 'place', 'ocean']],
    layout: {
      'text-font': ['NotoSans-Regular'],
      'text-field': ['get', 'name'],
      'text-size': 13,
      'text-letter-spacing': 0.2,
    },
    paint: {
      'text-color': '#6D6D6D',
    },
  },
  {
    id: 'places_subplace',
    type: 'symbol',
    source: 'protomaps',
    'source-layer': 'places',
    filter: ['==', 'pmap:kind', 'neighbourhood'],
    layout: {
      'text-field': '{name:en}',
      'text-font': ['NotoSans-Regular'],
      'text-size': 10,
      'text-transform': 'uppercase',
    },
    paint: {
      'text-color': '#6D6D6D',
      'text-halo-color': '#151515',
      'text-halo-width': 0.5,
    },
  },
  {
    id: 'places_city',
    type: 'symbol',
    source: 'protomaps',
    'source-layer': 'places',
    filter: ['==', 'pmap:kind', 'city'],
    layout: {
      'text-field': '{name:en}',
      'text-font': ['NotoSans-Regular'],
      'text-size': ['step', ['get', 'pmap:rank'], 0, 1, 12, 2, 10],
      'text-variable-anchor': ['bottom-left'],
      'text-radial-offset': 0.2,
    },
    paint: {
      'text-color': '#6D6D6D',
      'text-halo-color': '#151515',
      'text-halo-width': 1,
    },
  },
  {
    id: 'places_state',
    type: 'symbol',
    source: 'protomaps',
    'source-layer': 'places',
    filter: ['==', 'pmap:kind', 'state'],
    layout: {
      'text-field': '{name:en}',
      'text-font': ['NotoSans-Regular'],
      'text-size': 14,
      'text-radial-offset': 0.2,
      'text-anchor': 'center',
      'text-transform': 'uppercase',
      'text-letter-spacing': 0.1,
    },
    paint: {
      'text-color': '#6D6D6D',
      'text-halo-color': '#151515',
      'text-halo-width': 1,
    },
  },
  {
    id: 'places_country',
    type: 'symbol',
    source: 'protomaps',
    'source-layer': 'places',
    filter: ['==', 'place', 'country'],
    layout: {
      'text-field': '{name:en}',
      'text-font': ['NotoSans-Regular'],
      'text-size': 10,
    },
    paint: {
      'text-color': '#6D6D6D',
      'text-halo-color': '#151515',
      'text-halo-width': 1,
    },
  },
]
